name: makanku
description: "submission"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  google_fonts: ^6.3.0
  sqflite: ^2.4.2
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
