name: mascan
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  gap: ^3.0.1
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  flutter_riverpod: ^2.6.1
  tflite_flutter: ^0.11.0
  firebase_core: ^3.15.2
  firebase_ml_model_downloader: ^0.3.3+8
  google_generative_ai: ^0.4.7
  camera: ^0.11.2
  app_settings: ^6.1.1
  permission_handler: ^12.0.1
  package_info_plus: ^8.3.1
  fluttertoast: ^8.2.12
  logger: ^2.6.1
  dartz: ^0.10.1
  icons_plus: ^5.0.0
  google_fonts: ^6.3.0
  auto_injector: ^2.1.1
  envied: ^1.2.0
  image: ^4.5.4
  path_provider: ^2.1.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  envied_generator: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/banners/
